FROM jenkins/jnlp-slave:alpine

USER root

RUN mkdir 
COPY ./bin/helm /usr/local/bin/helm
RUN chmod +x /usr/local/bin/helm \
    && mkdir /home/jenkins/.kube
COPY ./kube/kubeconf /home/jenkins/.kube/config

COPY ./certs/ca.cert.pem /usr/local/share/ca-certificates/ca.crt
RUN apk --update add update-ca-certificates \
    && update-ca-certificates \
    && keytool -import -alias ssii.com -file /usr/local/share/ca-certificates/ca.crt -keystore "$JAVA_HOME/jre/lib/security/cacerts" -storepass changeit -trustcacerts -noprompt \
    && echo "Asia/Chongqing" > /etc/timezone \
    && rm -rf /var/lib/apt/lists/* \
    && rm /var/cache/apk/* \
    && chown jenkins.jenkins /home/jenkins/.kube \
    && helm init --client-only

USER jenkins
