FROM jenkins/jnlp-slave:3.27-1

USER root

COPY ./certs/ca.cert.pem /usr/local/share/ca-certificates/ca.crt

RUN update-ca-certificates

RUN keytool -import -alias ssii.com -file /usr/local/share/ca-certificates/ca.crt -keystore "$JAVA_HOME/jre/lib/security/cacerts" -storepass changeit -trustcacerts -noprompt

RUN echo "Asia/Chongqing" > /etc/timezone

RUN mkdir -p /etc/resolvconf/resolv.conf.d && echo "nameserver 10.96.0.10" >> /etc/resolvconf/resolv.conf.d/base

USER jenkins
