apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitea
  namespace: env
spec:
  tls:
  - hosts:
    - gitea.rdp.dev
    secretName: ingress-secrets
  rules:
  - host: gitea.rdp.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: gitea
          servicePort: 80