# Source: istio/charts/kiali/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: kiali.ssii.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kiali
              servicePort: 20001
  tls:
  - secretName: istio-ingress-metrics-certs
    hosts:
      - kiali.ssii.com

---
# Source: istio/charts/prometheus/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: istio-system
  labels:
    app: prometheus
    chart: prometheus
    heritage: Tiller
    release: istio
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: prometheus.ssii.com
      http:
        paths:
          - path: /
            backend:
              serviceName: prometheus
              servicePort: 9090
  tls:
  - secretName: istio-ingress-metrics-certs
    hosts:
      - prometheus.ssii.com

---
# Source: istio/charts/tracing/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: istio-tracing
  namespace: istio-system
  labels:
    app: jaeger
    chart: tracing
    heritage: Tiller
    release: istio
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: tracing.ssii.com
    http:
      paths:
        - path: /
          backend:
            serviceName: tracing
            servicePort: 80
  tls:
  - secretName: istio-ingress-metrics-certs
    hosts:
      - tracing.ssii.com

---
# Source: istio/charts/grafana/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: istio-system
  labels:
    app: grafana
    chart: grafana
    heritage: Tiller
    release: istio
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: grafana.ssii.com
    http:
      paths:
        - path: /
          backend:
            serviceName: grafana
            servicePort: 3000
  tls:
  - secretName: istio-ingress-metrics-certs
    hosts:
      - grafana.ssii.com
