apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitea
  namespace: devops
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # certmanager.k8s.io/cluster-issuer: ClusterIssuer
    # nginx.nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - gitea.ssii.com
    secretName: ingress-certs
  rules:
  - host: gitea.ssii.com
    http:
      paths:
      - backend:
          serviceName: gitea
          servicePort: 3000
