apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitea
  namespace: env
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - gitea.rdp.dev
    secretName: ingress-certs
  rules:
  - host: gitea.rdp.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: gitea
          servicePort: 80