apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitea
  namespace: env
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - gitea.rdp.dev
    secretName: ingress-certs
  rules:
  - host: gitea.rdp.dev
    http:
      paths:
      - backend:
          serviceName: gitea
          servicePort: 80