apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: devops
  labels:
    name: gitea
spec:
  ports:
    - name: gitea
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: gitea-ssh
      protocol: TCP
      port: 22
      targetPort: 22
  selector:
    name: gitea
  type: NodePort
