apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb-config
data:
  config: |
    address-pools:
    - name: metallb-ips
      protocol: layer2
      addresses:
      - 172.30.80.27-172.30.80.30