apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-ingress-metrics-certs
  namespace: istio-system
spec:
  secretName: istio-ingress-metrics-certs
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
  commonName: ssii.com
  dnsNames:
  - grafana.ssii.com
  - prometheus.ssii.com
  - kiali.ssii.com
  - tracing.ssii.com
  