apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jx-ingress-certs
  namespace: jx
spec:
  secretName: jx-ingress-certs
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
  commonName: jx.rdp.dev
  dnsNames:
    - *.jx.rdp.dev
