apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certs
  namespace: devops
spec:
  secretName: ingress-certs
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: ssii.com
  organization:
  - RDP Dev CA
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - ssii.com
  - chartmuseum.ssii.com
  - keycloak.ssii.com
  - jenkins.ssii.com
  - nexus.ssii.com
  - harbor.ssii.com
  - containers.ssii.com
  - kubeapps.ssii.com
  - gitea.ssii.com
  - kubesphere.ssii.com
  - registry.ssii.com
  - repo.ssii.com
  