apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-certs
  namespace: devops
spec:
  secretName: ingress-certs
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: ssii.com
  organization:
  - RDP Dev CA
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  dnsNames:
  - ssii.com
  - chartmuseum.ssii.com
  - keycloak.ssii.com
  - jenkins.ssii.com
  - nexus.ssii.com
  - harbor.ssii.com
  - containers.ssii.com
  - kubeapps.ssii.com
  - gitea.ssii.com
  - kubesphere.ssii.com
  