---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: jx-ingress-certs-acme
  namespace: jx
spec:
  secretName: jx-ingress-certs-acme
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: jx.ssii.com
  dnsNames:
  - chartmuseum.jx.ssii.com
  - docker-registry.jx.ssii.com
  - gitea-gitea.jx.ssii.com
  - jenkins.jx.ssii.com
  - monocular.jx.ssii.com
  - nexus.jx.ssii.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - chartmuseum.jx.ssii.com
      - docker-registry.jx.ssii.com
      - gitea-gitea.jx.ssii.com
      - jenkins.jx.ssii.com
      - monocular.jx.ssii.com
      - nexus.jx.ssii.com
    # - http01:
    #     ingress: chartmuseum
    #   domains:
    #   - chartmuseum.jx.ssii.com
    # - http01:
    #     ingress: docker-registry
    #   domains:
    #   - docker-registry.jx.ssii.com
    # - http01:
    #     ingress: gitea-gitea
    #   domains:
    #   - gitea-gitea.jx.ssii.com
    # - http01:
    #     ingress: jenkins
    #   domains:
    #   - jenkins.jx.ssii.com
    # - http01:
    #     ingress: monocular
    #   domains:
    #   - monocular.jx.ssii.com
    # - http01:
    #     ingress: nexus
    #   domains:
    #   - nexus.jx.ssii.com
