apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: gitlab-ingress-certs
  namespace: env
spec:
  secretName: gitlab-ingress-certs
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
  commonName: rdp.dev
  dnsNames:
  - gitlab.rdp.dev
  - registry.rdp.dev
  - minio.rdp.dev
  