---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jx-ingress-certs
  namespace: jx
spec:
  secretName: jx-ingress-certs
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: jx.rdp.dev
  dnsNames:
  - chartmuseum.jx.rdp.dev
  - docker-registry.jx.rdp.dev
  - gitea-gitea.jx.rdp.dev
  - jenkins.jx.rdp.dev
  - monocular.jx.rdp.dev
  - nexus.jx.rdp.dev
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - chartmuseum.jx.rdp.dev
      - docker-registry.jx.rdp.dev
      - gitea-gitea.jx.rdp.dev
      - jenkins.jx.rdp.dev
      - monocular.jx.rdp.dev
      - nexus.jx.rdp.dev
    # - http01:
    #     ingress: chartmuseum
    #   domains:
    #   - chartmuseum.jx.rdp.dev
    # - http01:
    #     ingress: docker-registry
    #   domains:
    #   - docker-registry.jx.rdp.dev
    # - http01:
    #     ingress: gitea-gitea
    #   domains:
    #   - gitea-gitea.jx.rdp.dev
    # - http01:
    #     ingress: jenkins
    #   domains:
    #   - jenkins.jx.rdp.dev
    # - http01:
    #     ingress: monocular
    #   domains:
    #   - monocular.jx.rdp.dev
    # - http01:
    #     ingress: nexus
    #   domains:
    #   - nexus.jx.rdp.dev
