apiVersion: v1
description: Git with a cup of tea, painless self-hosted git service
name: gitea
appVersion: 1.5.1
version: 0.0.3
home: https://gitea.io/
icon: https://gitea.io/images/favicon.png
keywords:
- git
- gitea
maintainers:
- name: cdrage
  email: charlie@charliedrage.com
