# apiVersion: extensions/v1beta1
# kind: Ingress
metadata:
  annotations:
    certmanager.io/cluster-issuer: ClusterIssuer
    # fabric8.io/generated-by: exposecontroller
    # kubernetes.io/ingress.class: nginx
    nginx.nginx.ingress.kubernetes.io/ssl-redirect: "false"
  # creationTimestamp: 2018-06-28T09:46:54Z
  # generation: 2
  # labels:
  #   provider: fabric8
  # name: chartmuseum
  # namespace: jx
  # resourceVersion: "649849"
  # selfLink: /apis/extensions/v1beta1/namespaces/jx/ingresses/chartmuseum
  # uid: 30e7d6c2-7ab8-11e8-a07e-000c2972e7e0
spec:
  # rules:
  # - host: chartmuseum.jx.ssii.com
  #   http:
  #     paths:
  #     - backend:
  #         serviceName: jenkins-x-chartmuseum
  #         servicePort: 8080
  tls:
  - hosts:
    - chartmuseum.jx.ssii.com
    secretName: jx-ingress-certs
# status:
#   loadBalancer:
#     ingress:
#     - {}
