apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: ClusterIssuer
    fabric8.io/generated-by: exposecontroller
    kubernetes.io/ingress.class: nginx
  # creationTimestamp: 2018-06-28T10:33:07Z
  # generation: 2
  labels:
    provider: fabric8
  name: gitea-gitea
  namespace: jx
  # resourceVersion: "655083"
  # selfLink: /apis/extensions/v1beta1/namespaces/jx/ingresses/gitea-gitea
  # uid: a5c0566c-7abe-11e8-a07e-000c2972e7e0
spec:
  rules:
  - host: gitea-gitea.jx.rdp.dev
    http:
      paths:
      - backend:
          serviceName: gitea-gitea
          servicePort: 80
  - host: gitea-gitea.jx.rdp.dev
    http:
      paths:
      - backend:
          serviceName: gitea-gitea
          servicePort: 80
      - backend:
          serviceName: gitea-gitea
          servicePort: 22
  tls:
  - hosts:
    - gitea-gitea.jx.rdp.dev
    secretName: jx-ingress-certs
status:
  loadBalancer:
    ingress:
    - {}
