apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: ClusterIssuer
    fabric8.io/generated-by: exposecontroller
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
  # creationTimestamp: 2018-06-28T09:46:54Z
  # generation: 2
  labels:
    provider: fabric8
  name: jenkins
  namespace: jx
  # resourceVersion: "652556"
  # selfLink: /apis/extensions/v1beta1/namespaces/jx/ingresses/jenkins
  # uid: 30ee20bb-7ab8-11e8-a07e-000c2972e7e0
spec:
  rules:
  - host: jenkins.jx.rdp.dev
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
  tls:
  - hosts:
    - jenkins.jx.rdp.dev
    secretName: jx-ingress-certs
status:
  loadBalancer:
    ingress:
    - {}
