# apiVersion: extensions/v1beta1
# kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: ClusterIssuer
    nginx.nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # fabric8.io/generated-by: exposecontroller
    # kubernetes.io/ingress.class: nginx
  # creationTimestamp: 2018-06-28T09:46:55Z
  # generation: 2
  labels:
    provider: fabric8
  name: nexus
  namespace: jx
  # resourceVersion: "655628"
  # selfLink: /apis/extensions/v1beta1/namespaces/jx/ingresses/nexus
  # uid: 319a33fb-7ab8-11e8-a07e-000c2972e7e0
spec:
  # rules:
  # - host: nexus.jx.ssii.com
  #   http:
  #     paths:
  #     - backend:
  #         serviceName: nexus
  #         servicePort: 80
  tls:
  - hosts:
    - nexus.jx.ssii.com
    secretName: jx-ingress-certs
# status:
#   loadBalancer:
#     ingress:
#     - {}
